provider:
  name: openfaas
  gateway: http://127.0.0.1:8080  # can be a remote server

functions:
  alpine-function:
    lang: dockerfile
    handler: ./alpinefunction
    image: functions/alpine:latest-multiarch
    platforms: linux/amd64,linux/arm64,linux/arm/7
